resume: null
save_dir: ../ckpt/
log_dir: tensorboard/
gpu: true
n_gpu: 1
metrics:
- _target_: srcs.model.metric.accuracy
- _target_: srcs.model.metric.precision
- _target_: srcs.model.metric.recall
- _target_: srcs.model.metric.f1
data:
  csv_path: ../data/processed_by_misha/train.csv
  images_dir: "../data/train/ml_ozon_\u0441ounterfeit_train_images/"
  test_images_dir: "../data/test/ml_ozon_\u0441ounterfeit_test_images/"
  id_col: ItemID
  target_col: resolution
  text_cols:
  - description
  - name_rus
  tabular_cols:
  - rating_1_count_scaled
  - rating_2_count_scaled
  - rating_3_count_scaled
  - rating_4_count_scaled
  - rating_5_count_scaled
  - comments_published_count_scaled
  - photos_published_count_scaled
  - videos_published_count_scaled
  - PriceDiscounted_scaled
  - item_time_alive_scaled
  - item_count_fake_returns7_scaled
  - item_count_fake_returns30_scaled
  - item_count_fake_returns90_scaled
  - item_count_sales7_scaled
  - item_count_sales30_scaled
  - item_count_sales90_scaled
  - item_count_returns7_scaled
  - item_count_returns30_scaled
  - item_count_returns90_scaled
  - GmvTotal7_scaled
  - GmvTotal30_scaled
  - GmvTotal90_scaled
  - ExemplarAcceptedCountTotal7_scaled
  - ExemplarAcceptedCountTotal30_scaled
  - ExemplarAcceptedCountTotal90_scaled
  - OrderAcceptedCountTotal7_scaled
  - OrderAcceptedCountTotal30_scaled
  - OrderAcceptedCountTotal90_scaled
  - ExemplarReturnedCountTotal7_scaled
  - ExemplarReturnedCountTotal30_scaled
  - ExemplarReturnedCountTotal90_scaled
  - ExemplarReturnedValueTotal7_scaled
  - ExemplarReturnedValueTotal30_scaled
  - ExemplarReturnedValueTotal90_scaled
  - ItemVarietyCount_scaled
  - ItemAvailableCount_scaled
  - seller_time_alive_scaled
  - name_len_scaled
  - description_len_scaled
  - name_word_count_scaled
  - description_word_count_scaled
  - caps_ratio_in_name_scaled
  - digits_in_name_ratio_scaled
  - "has_\u043A\u043E\u043F\u0438\u044F_description_scaled"
  - "has_\u043A\u043E\u043F\u0438\u044F_name_rus_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_description_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_name_rus_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_description_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_name_rus_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_description_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_name_rus_scaled"
  - brand_in_name_score_scaled
  - name_desc_similarity_scaled
  - word_repeat_ratio_scaled
  - special_char_ratio_scaled
  - has_ratings_scaled
  - has_brand_scaled
  - has_fake_returns_scaled
  - has_photo_scaled
  - has_video_scaled
  - has_comments_scaled
  - is_premium_brand_scaled
  - brand_frequency_scaled
  - has_tech_specs_scaled
  - desc_len_vs_category_scaled
  - log_price_scaled
  - log_price_minus_cat_median_scaled
  - robust_price_z_cat_scaled
  - price_zscore_cat_scaled
  - log_price_minus_brand_median_scaled
  - robust_price_z_brand_scaled
  - price_zscore_brand_scaled
  - price_vs_global_median_scaled
  - item_return_ratio_7_scaled
  - item_return_ratio_30_scaled
  - item_return_ratio_90_scaled
  - item_fake_return_ratio_7_scaled
  - item_fake_return_ratio_30_scaled
  - item_fake_return_ratio_90_scaled
  - sales_growth_7_30_scaled
  - return_recent_ratio_7_90_scaled
  - item_age_ratio_scaled
  - return_value_ratio_90_scaled
  - item_gmv_share_90_scaled
  - total_ratings_scaled
  - avg_rating_scaled
  - price_avg_rating_interact_scaled
  - rating_polarization_scaled
  - negative_ratio_scaled
  - rating_variance_scaled
  - seller_avg_item_price_scaled
  - seller_total_sales_90_scaled
  - seller_total_returns_90_scaled
  - seller_total_fake_returns_90_scaled
  - seller_avg_rating_scaled
  - seller_return_rate_90_scaled
  - seller_fake_return_rate_90_scaled
  - seller_category_entropy_scaled
  - seller_item_depth_scaled
  - seller_newbie_scaled
  - has_multiple_items_scaled
  - rating_skewness_scaled
  - sales_spike_7d_scaled
  - returns_spike_7d_scaled
  - brand_cat_rarity_scaled
  - is_rare_brand_cat_scaled
  - price_brand_cat_anomaly_scaled
  - brand_popularity_in_cat_scaled
  - seller_items_listed_expanding_scaled
  - seller_avg_price_expanding_scaled
  - price_deviation_from_seller_mean_scaled
  - seller_rating_trend_scaled
  - seller_price_volatility_scaled
  - brand_name_te
  - SellerID_te
  - CommercialTypeName4_te
  val_size: 0.1
data_test:
  csv_path: ../data/processed/test.csv
  images_dir: "../data/test/ml_ozon_\u0441ounterfeit_test_images/"
  id_col: ItemID
  text_cols:
  - description
  - name_rus
  tabular_cols:
  - rating_1_count_scaled
  - rating_2_count_scaled
  - rating_3_count_scaled
  - rating_4_count_scaled
  - rating_5_count_scaled
  - comments_published_count_scaled
  - photos_published_count_scaled
  - videos_published_count_scaled
  - PriceDiscounted_scaled
  - item_time_alive_scaled
  - item_count_fake_returns7_scaled
  - item_count_fake_returns30_scaled
  - item_count_fake_returns90_scaled
  - item_count_sales7_scaled
  - item_count_sales30_scaled
  - item_count_sales90_scaled
  - item_count_returns7_scaled
  - item_count_returns30_scaled
  - item_count_returns90_scaled
  - GmvTotal7_scaled
  - GmvTotal30_scaled
  - GmvTotal90_scaled
  - ExemplarAcceptedCountTotal7_scaled
  - ExemplarAcceptedCountTotal30_scaled
  - ExemplarAcceptedCountTotal90_scaled
  - OrderAcceptedCountTotal7_scaled
  - OrderAcceptedCountTotal30_scaled
  - OrderAcceptedCountTotal90_scaled
  - ExemplarReturnedCountTotal7_scaled
  - ExemplarReturnedCountTotal30_scaled
  - ExemplarReturnedCountTotal90_scaled
  - ExemplarReturnedValueTotal7_scaled
  - ExemplarReturnedValueTotal30_scaled
  - ExemplarReturnedValueTotal90_scaled
  - ItemVarietyCount_scaled
  - ItemAvailableCount_scaled
  - seller_time_alive_scaled
  - name_len_scaled
  - description_len_scaled
  - name_word_count_scaled
  - description_word_count_scaled
  - caps_ratio_in_name_scaled
  - digits_in_name_ratio_scaled
  - "has_\u043A\u043E\u043F\u0438\u044F_description_scaled"
  - "has_\u043A\u043E\u043F\u0438\u044F_name_rus_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_description_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_name_rus_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_description_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_name_rus_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_description_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_name_rus_scaled"
  - brand_in_name_score_scaled
  - name_desc_similarity_scaled
  - word_repeat_ratio_scaled
  - special_char_ratio_scaled
  - has_ratings_scaled
  - has_brand_scaled
  - has_fake_returns_scaled
  - has_photo_scaled
  - has_video_scaled
  - has_comments_scaled
  - is_premium_brand_scaled
  - brand_frequency_scaled
  - has_tech_specs_scaled
  - desc_len_vs_category_scaled
  - log_price_scaled
  - log_price_minus_cat_median_scaled
  - robust_price_z_cat_scaled
  - price_zscore_cat_scaled
  - log_price_minus_brand_median_scaled
  - robust_price_z_brand_scaled
  - price_zscore_brand_scaled
  - price_vs_global_median_scaled
  - item_return_ratio_7_scaled
  - item_return_ratio_30_scaled
  - item_return_ratio_90_scaled
  - item_fake_return_ratio_7_scaled
  - item_fake_return_ratio_30_scaled
  - item_fake_return_ratio_90_scaled
  - sales_growth_7_30_scaled
  - return_recent_ratio_7_90_scaled
  - item_age_ratio_scaled
  - return_value_ratio_90_scaled
  - item_gmv_share_90_scaled
  - total_ratings_scaled
  - avg_rating_scaled
  - price_avg_rating_interact_scaled
  - rating_polarization_scaled
  - negative_ratio_scaled
  - rating_variance_scaled
  - seller_avg_item_price_scaled
  - seller_total_sales_90_scaled
  - seller_total_returns_90_scaled
  - seller_total_fake_returns_90_scaled
  - seller_avg_rating_scaled
  - seller_return_rate_90_scaled
  - seller_fake_return_rate_90_scaled
  - seller_category_entropy_scaled
  - seller_item_depth_scaled
  - seller_newbie_scaled
  - has_multiple_items_scaled
  - rating_skewness_scaled
  - sales_spike_7d_scaled
  - returns_spike_7d_scaled
  - brand_cat_rarity_scaled
  - is_rare_brand_cat_scaled
  - price_brand_cat_anomaly_scaled
  - brand_popularity_in_cat_scaled
  - seller_items_listed_expanding_scaled
  - seller_avg_price_expanding_scaled
  - price_deviation_from_seller_mean_scaled
  - seller_rating_trend_scaled
  - seller_price_volatility_scaled
  - brand_name_te
  - SellerID_te
  - CommercialTypeName4_te
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: sberbank-ai/ruBERT-base
  model_name: sberbank-ai/ruBERT-base
data_loader:
  _target_: srcs.data_loader.data_loaders.get_dataloaders
  images_dir: "../data/train/ml_ozon_\u0441ounterfeit_train_images/"
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: sberbank-ai/ruBERT-base
    model_name: sberbank-ai/ruBERT-base
  tabular_cols:
  - rating_1_count_scaled
  - rating_2_count_scaled
  - rating_3_count_scaled
  - rating_4_count_scaled
  - rating_5_count_scaled
  - comments_published_count_scaled
  - photos_published_count_scaled
  - videos_published_count_scaled
  - PriceDiscounted_scaled
  - item_time_alive_scaled
  - item_count_fake_returns7_scaled
  - item_count_fake_returns30_scaled
  - item_count_fake_returns90_scaled
  - item_count_sales7_scaled
  - item_count_sales30_scaled
  - item_count_sales90_scaled
  - item_count_returns7_scaled
  - item_count_returns30_scaled
  - item_count_returns90_scaled
  - GmvTotal7_scaled
  - GmvTotal30_scaled
  - GmvTotal90_scaled
  - ExemplarAcceptedCountTotal7_scaled
  - ExemplarAcceptedCountTotal30_scaled
  - ExemplarAcceptedCountTotal90_scaled
  - OrderAcceptedCountTotal7_scaled
  - OrderAcceptedCountTotal30_scaled
  - OrderAcceptedCountTotal90_scaled
  - ExemplarReturnedCountTotal7_scaled
  - ExemplarReturnedCountTotal30_scaled
  - ExemplarReturnedCountTotal90_scaled
  - ExemplarReturnedValueTotal7_scaled
  - ExemplarReturnedValueTotal30_scaled
  - ExemplarReturnedValueTotal90_scaled
  - ItemVarietyCount_scaled
  - ItemAvailableCount_scaled
  - seller_time_alive_scaled
  - name_len_scaled
  - description_len_scaled
  - name_word_count_scaled
  - description_word_count_scaled
  - caps_ratio_in_name_scaled
  - digits_in_name_ratio_scaled
  - "has_\u043A\u043E\u043F\u0438\u044F_description_scaled"
  - "has_\u043A\u043E\u043F\u0438\u044F_name_rus_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_description_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_name_rus_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_description_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_name_rus_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_description_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_name_rus_scaled"
  - brand_in_name_score_scaled
  - name_desc_similarity_scaled
  - word_repeat_ratio_scaled
  - special_char_ratio_scaled
  - has_ratings_scaled
  - has_brand_scaled
  - has_fake_returns_scaled
  - has_photo_scaled
  - has_video_scaled
  - has_comments_scaled
  - is_premium_brand_scaled
  - brand_frequency_scaled
  - has_tech_specs_scaled
  - desc_len_vs_category_scaled
  - log_price_scaled
  - log_price_minus_cat_median_scaled
  - robust_price_z_cat_scaled
  - price_zscore_cat_scaled
  - log_price_minus_brand_median_scaled
  - robust_price_z_brand_scaled
  - price_zscore_brand_scaled
  - price_vs_global_median_scaled
  - item_return_ratio_7_scaled
  - item_return_ratio_30_scaled
  - item_return_ratio_90_scaled
  - item_fake_return_ratio_7_scaled
  - item_fake_return_ratio_30_scaled
  - item_fake_return_ratio_90_scaled
  - sales_growth_7_30_scaled
  - return_recent_ratio_7_90_scaled
  - item_age_ratio_scaled
  - return_value_ratio_90_scaled
  - item_gmv_share_90_scaled
  - total_ratings_scaled
  - avg_rating_scaled
  - price_avg_rating_interact_scaled
  - rating_polarization_scaled
  - negative_ratio_scaled
  - rating_variance_scaled
  - seller_avg_item_price_scaled
  - seller_total_sales_90_scaled
  - seller_total_returns_90_scaled
  - seller_total_fake_returns_90_scaled
  - seller_avg_rating_scaled
  - seller_return_rate_90_scaled
  - seller_fake_return_rate_90_scaled
  - seller_category_entropy_scaled
  - seller_item_depth_scaled
  - seller_newbie_scaled
  - has_multiple_items_scaled
  - rating_skewness_scaled
  - sales_spike_7d_scaled
  - returns_spike_7d_scaled
  - brand_cat_rarity_scaled
  - is_rare_brand_cat_scaled
  - price_brand_cat_anomaly_scaled
  - brand_popularity_in_cat_scaled
  - seller_items_listed_expanding_scaled
  - seller_avg_price_expanding_scaled
  - price_deviation_from_seller_mean_scaled
  - seller_rating_trend_scaled
  - seller_price_volatility_scaled
  - brand_name_te
  - SellerID_te
  - CommercialTypeName4_te
  target_col: resolution
  id_col: ItemID
  text_cols:
  - description
  - name_rus
  batch_size: 32
  num_workers: 16
test_data_loader:
  _target_: srcs.data_loader.data_loaders.get_test_dataloader
  images_dir: "../data/test/ml_ozon_\u0441ounterfeit_test_images/"
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: sberbank-ai/ruBERT-base
    model_name: sberbank-ai/ruBERT-base
  tabular_cols:
  - rating_1_count_scaled
  - rating_2_count_scaled
  - rating_3_count_scaled
  - rating_4_count_scaled
  - rating_5_count_scaled
  - comments_published_count_scaled
  - photos_published_count_scaled
  - videos_published_count_scaled
  - PriceDiscounted_scaled
  - item_time_alive_scaled
  - item_count_fake_returns7_scaled
  - item_count_fake_returns30_scaled
  - item_count_fake_returns90_scaled
  - item_count_sales7_scaled
  - item_count_sales30_scaled
  - item_count_sales90_scaled
  - item_count_returns7_scaled
  - item_count_returns30_scaled
  - item_count_returns90_scaled
  - GmvTotal7_scaled
  - GmvTotal30_scaled
  - GmvTotal90_scaled
  - ExemplarAcceptedCountTotal7_scaled
  - ExemplarAcceptedCountTotal30_scaled
  - ExemplarAcceptedCountTotal90_scaled
  - OrderAcceptedCountTotal7_scaled
  - OrderAcceptedCountTotal30_scaled
  - OrderAcceptedCountTotal90_scaled
  - ExemplarReturnedCountTotal7_scaled
  - ExemplarReturnedCountTotal30_scaled
  - ExemplarReturnedCountTotal90_scaled
  - ExemplarReturnedValueTotal7_scaled
  - ExemplarReturnedValueTotal30_scaled
  - ExemplarReturnedValueTotal90_scaled
  - ItemVarietyCount_scaled
  - ItemAvailableCount_scaled
  - seller_time_alive_scaled
  - name_len_scaled
  - description_len_scaled
  - name_word_count_scaled
  - description_word_count_scaled
  - caps_ratio_in_name_scaled
  - digits_in_name_ratio_scaled
  - "has_\u043A\u043E\u043F\u0438\u044F_description_scaled"
  - "has_\u043A\u043E\u043F\u0438\u044F_name_rus_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_description_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_name_rus_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_description_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_name_rus_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_description_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_name_rus_scaled"
  - brand_in_name_score_scaled
  - name_desc_similarity_scaled
  - word_repeat_ratio_scaled
  - special_char_ratio_scaled
  - has_ratings_scaled
  - has_brand_scaled
  - has_fake_returns_scaled
  - has_photo_scaled
  - has_video_scaled
  - has_comments_scaled
  - is_premium_brand_scaled
  - brand_frequency_scaled
  - has_tech_specs_scaled
  - desc_len_vs_category_scaled
  - log_price_scaled
  - log_price_minus_cat_median_scaled
  - robust_price_z_cat_scaled
  - price_zscore_cat_scaled
  - log_price_minus_brand_median_scaled
  - robust_price_z_brand_scaled
  - price_zscore_brand_scaled
  - price_vs_global_median_scaled
  - item_return_ratio_7_scaled
  - item_return_ratio_30_scaled
  - item_return_ratio_90_scaled
  - item_fake_return_ratio_7_scaled
  - item_fake_return_ratio_30_scaled
  - item_fake_return_ratio_90_scaled
  - sales_growth_7_30_scaled
  - return_recent_ratio_7_90_scaled
  - item_age_ratio_scaled
  - return_value_ratio_90_scaled
  - item_gmv_share_90_scaled
  - total_ratings_scaled
  - avg_rating_scaled
  - price_avg_rating_interact_scaled
  - rating_polarization_scaled
  - negative_ratio_scaled
  - rating_variance_scaled
  - seller_avg_item_price_scaled
  - seller_total_sales_90_scaled
  - seller_total_returns_90_scaled
  - seller_total_fake_returns_90_scaled
  - seller_avg_rating_scaled
  - seller_return_rate_90_scaled
  - seller_fake_return_rate_90_scaled
  - seller_category_entropy_scaled
  - seller_item_depth_scaled
  - seller_newbie_scaled
  - has_multiple_items_scaled
  - rating_skewness_scaled
  - sales_spike_7d_scaled
  - returns_spike_7d_scaled
  - brand_cat_rarity_scaled
  - is_rare_brand_cat_scaled
  - price_brand_cat_anomaly_scaled
  - brand_popularity_in_cat_scaled
  - seller_items_listed_expanding_scaled
  - seller_avg_price_expanding_scaled
  - price_deviation_from_seller_mean_scaled
  - seller_rating_trend_scaled
  - seller_price_volatility_scaled
  - brand_name_te
  - SellerID_te
  - CommercialTypeName4_te
  target_col: resolution
  id_col: ItemID
  text_cols:
  - description
  - name_rus
  batch_size: 32
  num_workers: 16
name: MultimodalModel
arch:
  _target_: srcs.model.model.get_model
  text_model_name: sberbank-ai/ruBERT-base
loss:
  _target_: torch.nn.BCEWithLogitsLoss
optimizer:
  _target_: torch.optim.AdamW
  lr: 2.0e-05
  weight_decay: 0.0001
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.2
  patience: 3
  min_lr: 1.0e-06
n_cpu: 16
batch_size: 32
learning_rate: 2.0e-05
weight_decay: 0.0001
scheduler_step_size: 50
scheduler_gamma: 0.1
status: train
trainer:
  epochs: 10
  logging_step: 100
  monitor: max f1/valid
  save_topk: 7
  early_stop: 10
  tensorboard: true
cwd: .
