resume: null
save_dir: ../ckpt/
log_dir: tensorboard/
gpu: true
n_gpu: 1
metrics:
- _target_: srcs.model.metric.accuracy
- _target_: srcs.model.metric.precision
- _target_: srcs.model.metric.recall
- _target_: srcs.model.metric.f1
data:
  csv_path: ../data/processed/train.csv
  images_dir: "../data/train/ml_ozon_\u0441ounterfeit_train_images/"
  id_col: ItemID
  target_col: resolution
  text_cols:
  - description
  - name_rus
  tabular_cols:
  - ItemID
  - rating_1_count_scaled
  - rating_2_count_scaled
  - rating_3_count_scaled
  - rating_4_count_scaled
  - rating_5_count_scaled
  - comments_published_count_scaled
  - photos_published_count_scaled
  - videos_published_count_scaled
  - PriceDiscounted_scaled
  - item_time_alive_scaled
  - item_count_fake_returns7_scaled
  - item_count_fake_returns30_scaled
  - item_count_fake_returns90_scaled
  - item_count_sales7_scaled
  - item_count_sales30_scaled
  - item_count_sales90_scaled
  - item_count_returns7_scaled
  - item_count_returns30_scaled
  - item_count_returns90_scaled
  - GmvTotal7_scaled
  - GmvTotal30_scaled
  - GmvTotal90_scaled
  - ExemplarAcceptedCountTotal7_scaled
  - ExemplarAcceptedCountTotal30_scaled
  - ExemplarAcceptedCountTotal90_scaled
  - OrderAcceptedCountTotal7_scaled
  - OrderAcceptedCountTotal30_scaled
  - OrderAcceptedCountTotal90_scaled
  - ExemplarReturnedCountTotal7_scaled
  - ExemplarReturnedCountTotal30_scaled
  - ExemplarReturnedCountTotal90_scaled
  - ExemplarReturnedValueTotal7_scaled
  - ExemplarReturnedValueTotal30_scaled
  - ExemplarReturnedValueTotal90_scaled
  - ItemVarietyCount_scaled
  - ItemAvailableCount_scaled
  - seller_time_alive_scaled
  - price_vs_cat_median_scaled
  - name_len_scaled
  - name_word_count_scaled
  - "has_\u043A\u043E\u043F\u0438\u044F_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_scaled"
  - brand_in_name_score_scaled
  - has_ratings_scaled
  - has_brand_scaled
  - has_fake_returns_scaled
  - brand_name_te
  - SellerID_te
  - CommercialTypeName4_te
  val_size: 0.1
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: cointegrated/rubert-tiny2
  model_name: cointegrated/rubert-tiny2
data_loader:
  _target_: srcs.data_loader.data_loaders.get_dataloaders
  images_dir: "../data/train/ml_ozon_\u0441ounterfeit_train_images/"
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: cointegrated/rubert-tiny2
    model_name: cointegrated/rubert-tiny2
  tabular_cols:
  - ItemID
  - rating_1_count_scaled
  - rating_2_count_scaled
  - rating_3_count_scaled
  - rating_4_count_scaled
  - rating_5_count_scaled
  - comments_published_count_scaled
  - photos_published_count_scaled
  - videos_published_count_scaled
  - PriceDiscounted_scaled
  - item_time_alive_scaled
  - item_count_fake_returns7_scaled
  - item_count_fake_returns30_scaled
  - item_count_fake_returns90_scaled
  - item_count_sales7_scaled
  - item_count_sales30_scaled
  - item_count_sales90_scaled
  - item_count_returns7_scaled
  - item_count_returns30_scaled
  - item_count_returns90_scaled
  - GmvTotal7_scaled
  - GmvTotal30_scaled
  - GmvTotal90_scaled
  - ExemplarAcceptedCountTotal7_scaled
  - ExemplarAcceptedCountTotal30_scaled
  - ExemplarAcceptedCountTotal90_scaled
  - OrderAcceptedCountTotal7_scaled
  - OrderAcceptedCountTotal30_scaled
  - OrderAcceptedCountTotal90_scaled
  - ExemplarReturnedCountTotal7_scaled
  - ExemplarReturnedCountTotal30_scaled
  - ExemplarReturnedCountTotal90_scaled
  - ExemplarReturnedValueTotal7_scaled
  - ExemplarReturnedValueTotal30_scaled
  - ExemplarReturnedValueTotal90_scaled
  - ItemVarietyCount_scaled
  - ItemAvailableCount_scaled
  - seller_time_alive_scaled
  - price_vs_cat_median_scaled
  - name_len_scaled
  - name_word_count_scaled
  - "has_\u043A\u043E\u043F\u0438\u044F_scaled"
  - "has_\u0440\u0435\u043F\u043B\u0438\u043A\u0430_scaled"
  - "has_\u0430\u043D\u0430\u043B\u043E\u0433_scaled"
  - "has_\u0441\u043E\u0432\u043C\u0435\u0441\u0442\u0438\u043C\u044B\u0439_scaled"
  - brand_in_name_score_scaled
  - has_ratings_scaled
  - has_brand_scaled
  - has_fake_returns_scaled
  - brand_name_te
  - SellerID_te
  - CommercialTypeName4_te
  target_col: resolution
  id_col: ItemID
  text_cols:
  - description
  - name_rus
  batch_size: 64
  num_workers: 16
name: MultimodalModel
arch:
  _target_: srcs.model.model.get_model
  text_model_name: cointegrated/rubert-tiny2
loss:
  _target_: torch.nn.BCEWithLogitsLoss
optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-05
  weight_decay: 0.0001
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.2
  patience: 3
  min_lr: 1.0e-06
n_cpu: 16
batch_size: 64
learning_rate: 1.0e-05
weight_decay: 0.0001
scheduler_step_size: 50
scheduler_gamma: 0.1
status: train
trainer:
  epochs: 30
  logging_step: 100
  monitor: max f1/valid
  save_topk: 7
  early_stop: 10
  tensorboard: true
cwd: .
