resume: null
save_dir: ckpt/
log_dir: tensorboard/
gpu: true
n_gpu: 1
metrics:
- _target_: srcs.model.metric.accuracy
- _target_: srcs.model.metric.precision
- _target_: srcs.model.metric.recall
- _target_: srcs.model.metric.f1
data:
  csv_path: "../data/train/ml_ozon_\u0441ounterfeit_train.csv"
  images_dir: "../data/train/ml_ozon_\u0441ounterfeit_train_images/"
  id_col: ItemID
  target_col: resolution
  text_cols:
  - brand_name
  - description
  - name_rus
  - CommercialTypeName4
  tabular_cols:
  - rating_1_count
  - rating_2_count
  - rating_3_count
  - rating_4_count
  - rating_5_count
  - comments_published_count
  - photos_published_count
  - videos_published_count
  - PriceDiscounted
  - item_time_alive
  - item_count_fake_returns7
  - item_count_fake_returns30
  - item_count_fake_returns90
  - item_count_sales7
  - item_count_sales30
  - item_count_sales90
  - item_count_returns7
  - item_count_returns30
  - item_count_returns90
  - GmvTotal7
  - GmvTotal30
  - GmvTotal90
  - ExemplarAcceptedCountTotal7
  - ExemplarAcceptedCountTotal30
  - ExemplarAcceptedCountTotal90
  - OrderAcceptedCountTotal7
  - OrderAcceptedCountTotal30
  - OrderAcceptedCountTotal90
  - ExemplarReturnedCountTotal7
  - ExemplarReturnedCountTotal30
  - ExemplarReturnedCountTotal90
  - ExemplarReturnedValueTotal7
  - ExemplarReturnedValueTotal30
  - ExemplarReturnedValueTotal90
  - ItemVarietyCount
  - ItemAvailableCount
  - seller_time_alive
  - SellerID
  val_size: 0.1
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: cointegrated/rubert-tiny2
  model_name: cointegrated/rubert-tiny2
data_loader:
  _target_: srcs.data_loader.data_loaders.get_dataloaders
  images_dir: "../data/train/ml_ozon_\u0441ounterfeit_train_images/"
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: cointegrated/rubert-tiny2
    model_name: cointegrated/rubert-tiny2
  tabular_cols:
  - rating_1_count
  - rating_2_count
  - rating_3_count
  - rating_4_count
  - rating_5_count
  - comments_published_count
  - photos_published_count
  - videos_published_count
  - PriceDiscounted
  - item_time_alive
  - item_count_fake_returns7
  - item_count_fake_returns30
  - item_count_fake_returns90
  - item_count_sales7
  - item_count_sales30
  - item_count_sales90
  - item_count_returns7
  - item_count_returns30
  - item_count_returns90
  - GmvTotal7
  - GmvTotal30
  - GmvTotal90
  - ExemplarAcceptedCountTotal7
  - ExemplarAcceptedCountTotal30
  - ExemplarAcceptedCountTotal90
  - OrderAcceptedCountTotal7
  - OrderAcceptedCountTotal30
  - OrderAcceptedCountTotal90
  - ExemplarReturnedCountTotal7
  - ExemplarReturnedCountTotal30
  - ExemplarReturnedCountTotal90
  - ExemplarReturnedValueTotal7
  - ExemplarReturnedValueTotal30
  - ExemplarReturnedValueTotal90
  - ItemVarietyCount
  - ItemAvailableCount
  - seller_time_alive
  - SellerID
  target_col: resolution
  id_col: ItemID
  text_cols:
  - brand_name
  - description
  - name_rus
  - CommercialTypeName4
  batch_size: 64
  num_workers: 8
name: MultimodalModel
arch:
  _target_: srcs.model.model.get_model
  text_model_name: cointegrated/rubert-tiny2
loss:
  _target_: torch.nn.BCEWithLogitsLoss
optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-07
  weight_decay: 1.0e-06
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.2
  patience: 3
  min_lr: 1.0e-06
n_cpu: 8
batch_size: 64
learning_rate: 1.0e-07
weight_decay: 1.0e-06
scheduler_step_size: 50
scheduler_gamma: 0.1
status: train
trainer:
  epochs: 10
  logging_step: 100
  monitor: min loss/valid
  save_topk: 7
  early_stop: 10
  tensorboard: true
cwd: .
